name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create addon ZIP
        run: |
          mkdir -p package/CatResources

          rsync -av \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="package" \
            ./ package/CatResources/

          cd package
          zip -r "../CatResources-${GITHUB_REF_NAME}.zip" CatResources

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          files: CatResources-${{ github.ref_name }}.zip